import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import { ConvexClientProvider } from "@/providers/convex-provider";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
} from "@clerk/nextjs";
import Navbar from "./components/Navbar";
import { Theme } from "@radix-ui/themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <Theme>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <ConvexClientProvider>
              <Navbar />
              <main>
                <SignedIn>{children}</SignedIn>
                <SignedOut>
                  <div className="flex flex-col items-center justify-center min-h-[60vh]">
                    <p className="mb-4 text-lg text-gray-600">
                      Please sign in to access the app features.
                    </p>
                    <SignInButton />
                  </div>
                </SignedOut>
              </main>
            </ConvexClientProvider>
          </body>
        </html>
      </Theme>
    </ClerkProvider>
  );
}
